dist: xenial

language: node_js

node_js:
  - '10'

cache:
  npm: true

install:
  - npm ci
  - npm run install:peers

script:
  - npm run lint
  - npm test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
