dist: xenial

language: node_js

node_js:
  - '10'

cache:
  npm: true

install:
  - npm ci
  - npm run install:peers

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm test -- --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - ./smoke.sh
