name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run test -- --coverage
    - uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: 47283c50a0f1654abe1454ac936de832b4c668e579eb10c1aefa1545e4e77e1d
    - run: npm run e2e
  deploy:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Get full tag
      id: full_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: npm publish
    - run: ./bin/smoke.sh
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        TAG: ${{ steps.full_tag.outputs.VERSION }}
